name: FinNetX Compliance CI

on:
  push:
    branches: [ "main" ]
  issues:
    types: [opened]

jobs:
  compliance_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run commit compliance check
        run: |
          msg=$(git log -1 --pretty=%B)
          echo "🔎 Commit message: $msg"
          if echo "$msg" | grep -iq "WIP"; then
            echo "❌ WIP commits are not allowed."
            exit 1
          fi
          echo "✅ Commit message passed compliance check."

      - name: Log issue to Google Sheets (via Zapier webhook)
        run: |
          curl -X POST https://hooks.zapier.com/hooks/catch/YOUR_ZAP_ID/ \
          -H "Content-Type: application/json" \
          -d '{"title": "${{ github.event.issue.title }}", "assignee": "${{ github.event.issue.assignee.login }}"}'
